#pragma once
#include <SDL3/SDL.h>

#include "Entity.h"
#include "GameState.h"
#include "SceneManager.h"
#include "TextEntity.h"
#include "TextureManager.h"

/*
## SINGLETON: GameManager - manages the overall game state
  - track all run details
    - modifier, decks, cycle, score, ...
  - methods to fetch options from deck
  - method to select an option
  - keep history details (actions taken, outcomes, ...)
  - current GameState
    - provides GameState to ScreenManager to trigger renderer
    - houses all state machine logic to transition between GameStates
  - connects to SDL event handler
    - show options for cards
    - transition between currently selected card
*/

// struct ProductState {
//   string genre;           // RPG, Adventure, Strategy, ...
//   string platform;        // PC, Console, Mobile
//   string targetAudience;  // Kids, Teens, Adults
//   string artStyle;        // Pixel Art, 3D, Hand-drawn
//   string type;            // Single-player, Multiplayer, MMO, turn-based
// };

// TODO:
// - convert string to enums for the different options
// - add the modifiers for different card options
// - allow for multi-genre / platform
// - track progression
// - track full game details

// Thoughts:
// - each card can take the state object in and return an updated version
// - each card function is added as a reference to a vector
// - state is generated by taking the starting state then applying each card in
// sequence
// - each time a card is added we recalculate then cache the current state for
// rendering

class GameManager {
 private:
  GameState* state = nullptr;
  SceneManager* sceneManager = nullptr;
  TextureManager* textureManager = nullptr;
  uint64_t keyHoldStart = 0;                 // milliseconds
  const uint64_t KEY_HOLD_THRESHOLD = 1000;  // milliseconds
  // TODO: ensure this is reset to 0 when scene is changed
  int selectedOptionIndex = 0;

 protected:
  void longPressAction();
  void shortPressAction();

 public:
  GameManager(GameState* state, TextureManager* textureManager);
  ~GameManager();

  SceneManager::Scene getCurrentScene() const;
  std::vector<Entity*> getEntitiesForCurrentScene() const;
  SDL_AppResult handleEvent(SDL_Event* event);
};